// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://teexqwlnfdlcruqbmwuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlZXhxd2xuZmRsY3J1cWJtd3V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjU0NTksImV4cCI6MjA3MzEwMTQ1OX0.q9TO3T7SjEw81XSk5vmyAt4Ls77-BwrXxCHsA82B4i0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});