// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getCSRFToken } from '@/lib/csrf';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validação para desenvolvimento
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables. Please check your .env file.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage, // ✅ CORREÇÃO: Usar localStorage para persistir sessão entre recarregamentos
    persistSession: true,
    autoRefreshToken: true,
    // Vamos permitir que o Supabase processe automaticamente os tokens na URL
    // (necessário para fluxos como recuperação de senha).
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      // ✅ PROTEÇÃO CSRF: Adicionar token CSRF em todas as requisições
      'X-CSRF-Token': getCSRFToken() || '',
    },
  },
});